config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'
  get 'home', to: "projects#index"
  get 'register', to: "users#new"
  resources :users, only: [:create] 
  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  resources :sessions, only: [:create]
  get 'ui(/:action)', controller: 'ui'

  resources :projects, only: [:index, :new, :create] do 
    member do 
      patch :complete
    end 
  end 
  
  get "forgot_password", to: "forgot_passwords#new"
  resources :forgot_passwords, only: [:create]
  get "forgot_password_confirmation", to: "forgot_passwords#confirm"
  resources :password_resets, only: [:show, :create] 
  get "expired_token", to: "password_resets#expired_token"

end

app/models/project.rb
class Project < ActiveRecord::Base 
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :volume
  validates_presence_of :amount_due
  validates_presence_of :client_name
  belongs_to :user
end 

app/models/user.rb
class User < ActiveRecord::Base 
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password 
  validates_uniqueness_of :email 
  has_secure_password 
  has_many :projects
  
  before_create :generate_token 
  
  def admin?
    admin = true
  end

  def generate_token 
    self.token = SecureRandom.urlsafe_base64 
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_user
    redirect_to login_path unless current_user
  end
  
  def current_user 
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user, :require_user
end

app/controllers/forgot_passwords_controller.rb
class ForgotPasswordsController < ApplicationController 

  def create
    user = User.where(email: params[:email]).first
    if user
      Usermailer.send_forgot_password_email(user).deliver
      redirect_to forgot_password_confirmation_path
    else 
      if params[:email].blank? 
        flash[:danger] = "Email cannot be blank!"
      else  
        flash[:danger] = "This email was not found in our database. Please try again!" 
      end 
      redirect_to forgot_password_path
    end 
  end

end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController 

end 

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController 
  def show
    user = User.where(token: params[:id]).first
    if user 
      @token = user.token 
    else 
      redirect_to expired_token_path
    end 
  end

  def create
    user = User.where(token: params[:token]).first
    if user 
      user.password = params[:password]
      user.generate_token 
      user.save 
      flash[:success] = "Your password has been changed."
      redirect_to login_path
    else 
      redirect_to expired_token_path
    end  
  end
end  

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 
  before_filter :require_user
  def index
    @projects = current_user.projects.order("created_at DESC")
  end
  def new
    @project = Project.new 
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.status = "On Going"
    if @project.save
      flash[:success] = "You have successfully save a new project."
      Usermailer.send_email_on_new_project(@project.user, @project).deliver_now
      redirect_to home_path
    else 
      flash[:danger] = "Your project was not saved."
      render :new
    end 
  end

  def complete
    @project = Project.find(params[:id])
    @project.user = current_user
    @project.update_attribute(:status, "Completed")
    Usermailer.send_email_on_completed_project(@project.user, @project).deliver_now
    redirect_to home_path
  end

  private 

  def project_params
    params.require(:project).permit(:title, :description, :volume, :amount_due, :client_name, :status)
  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome to Flowlance!"
      redirect_to home_path
    else 
      redirect_to login_path
      flash[:danger] = "Your email and password don't match."
    end 
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You are logged out."
    redirect_to root_path
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save    
      Usermailer.send_welcome_email(@user).deliver_now
      redirect_to login_path  
    else 
      flash[:danger] = "Please correct the errors."
      render :new
    end 
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :admin)
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forgot_passwords/confirm.html.erb
<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <p>We have sent you an email with instruction to reset your password.</p>
      </div>
    </div> <!-- row --> 
  </div> <!-- container -->
</div> <!-- main-content -->

app/views/forgot_passwords/new.html.erb
<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>
        <h1 class="text-center">Forgot Password?</h1>
        <p class="text-center lead">We will send you an email with a link to reset your password.</p>
        <%= form_tag forgot_passwords_path, class: 'login' do %>
          <div class='form-group'>
            <%= label_tag :email, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= email_field_tag :email, nil, class: "form-control", placeholder: "Email" %>
            </div>
          </div>
          <div class='col-md-offset-2'>
            <div class='form-group'>
              <div class='col-sm-offeset-2 col-sm-10'>
                <%= submit_tag "Send Email", class: "btn btn-primary" %> 
              </div>
            </div>
          </div>
        <% end %> 
      </div>
    </div> <!-- row --> 
  </div> <!-- container -->
</div> <!-- main-content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flowlance | Project Manager for Freelancers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'shared/header' %>
  </header>
  <%= yield %>

  <footer>
    <%= render 'shared/footer' %>
  </footer> 
</body>
</html>

app/views/pages/front.html.erb
<div class="jumbotron">
  <div class='container'>
    <div class='row text-center'>
      <div class='col-md-12'>
        <h1 class='text-center'>Flowlance</h1>
        <h2 class='text-center'>The best way for freelancers to manage projects</h2>
        <p>Flowlance helps you save time and money by providing a easier way</p>
        <p>to manage your projects so you can focus on your work.</p>
        <hr/>
        <p>Register and start saving time and money</p>
        <%= link_to "Get Started", register_path, class: 'btn btn-primary btn-lg' %> 
      </div>
    </div>
  </div>
</div>

app/views/password_resets/expired_token.html.erb
<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class= "well">
        <p class="text-center lead">Your reset password link has expired.</p>
      </div>
    </div> <!-- row --> 
  </div> <!-- container -->
</div> <!-- main-content -->

app/views/password_resets/show.html.erb
 <div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>
        <%= form_tag password_resets_path, class: 'login' do %> 
        <h2 class="text-center">Reset Your Password</h2>
          <div class='form-group'>
            <%= label_tag :password, nil, class: "col-sm-2 control-label" %>  
            <div class='col-sm-10'>
              <%= password_field_tag :password, nil, class: "form-control", placeholder: "New Password" %> 
              <%= hidden_field_tag :token, @token %> 
            </div>
          </div>
          <div class='col-md-offset-2'>
            <div class='form-group'>
              <div class='col-sm-offeset-2 col-sm-10'>
                <%= submit_tag "Reset Password", class: "btn btn-primary" %> 
              </div>
            </div>
          </div>
          <% end %> 
      </div>
    </div> <!-- row --> 
  </div> <!-- container -->
</div> <!-- main-content -->

app/views/projects/index.html.erb
<p class='text-center lead'>
  All your projects are listed below:
</p>

<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='well'>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Description</th>
              <th>Volume</th>
              <th>Amount Due</th>
              <th>Client Name</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            <% @projects.each do |project| %> 
            <tr>
              <td><%= project.title %></td>
              <td><%= project.description %></td>
              <td><%= project.volume %></td>
              <td>USD <%= project.amount_due %></td>
              <td><%= project.client_name %></td>
              <td><%= link_to project.status, complete_project_path(project), method: :patch, class: (project.status == "On Going" ? "btn btn-warning" : "btn btn-success") %></td>
            </tr>
            <% end %> 
          </tbody>
        </table>
      </div>
    </div>
    <p class='lead text-center'>Record a new project: <%= link_to "New Project", new_project_path, class: 'btn btn-primary' %></p>
  </div>
</div> 

app/views/projects/new.html.erb
<p class='text-center lead'>
  Please enter the details of a new project:
</p>
<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-sm-offset-3'>
        <%= form_for @project do |f| %> 
          <%= render 'shared/errors', obj: @project %> 
          <div class='form-group'>
            <%= f.label :title, nil,  class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.text_field :title, class: "form-control", placeholder: "Project Title" %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :description, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.text_field :description, class: "form-control", placeholder: "Project Description" %> 
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :volume, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.text_field :volume, class: "form-control", placeholder: "Project Volume" %> 
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :amount_due, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.text_field :amount_due, class: "form-control", placeholder: "Amount Due" %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :client_name, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.text_field :client_name, class: "form-control", placeholder: "Client Name" %> 
            </div>
          </div>
          <div class='col-md-offset-2'>
            <div class='form-group'>
              <div class='col-sm-offeset-2 col-sm-10'>
                <%= f.submit "Save Project", class: "btn btn-primary" %> 
              </div>
            </div>
          </div> 
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger span5">
      <h5>Please fix the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='container'></div>
<footer> 
  <div class='container'>
    <div class='row'>
       <div class='col-xs-6 col-sm-4'>
        <h4>Links</h4>
        <ul class='list-unstyled'> 
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </div>
       <div class='col-xs-6 col-sm-4'>
        <h4>Stay In Touch</h4>
          <ul class='list-unstyled'>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
          </ul>
      </div>
      <div class='col-xs-12 col-sm-4'>
        <h4>Contact Us</h4>
        <ul class='list-unstyled'>
          <li><span class='glyphicon glyphicon-phone'></span> 020 456 2323</li>
          <li><span class='glyphicon glyphicon-envelope'></span> info@flowlance.com</li>
          <li><span class='glyphicon glyphicon-map-marker'></span> 14 Riverside Drive, Lavington, Nairobi</li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class='container'>
    <div class="navbar-header">
      <% if current_user %> 
      <%= link_to "Flowlance", home_path, class: "navbar-brand" %> 
      <% else %> 
      <%= link_to "Flowlance", root_path, class: "navbar-brand" %> 
      <% end %> 
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %> 
        <li><%= link_to "Logout", logout_path %></li>
      <% else %> 
        <li><%= link_to "Login", login_path %></li>
      <% end %> 
    </ul>
  </div> 
</div>

app/views/users/new.html.erb
<p class='text-center lead'>
  Please Register Here
</p>
<div class='main-content'>
  <div class='container'>
    <div class='row'>
      <div class='col-md-6 col-md-offset-3'>
        <%= form_for @user, html: { class: "horizontal-form", id: "payment-form" } do |f|   %> 
          <%= render "shared/errors", obj: @user %> 
          <div class='form-group'>
            <%= f.label :name, nil, class: 'col-sm-2 control-label' %>  
            <div class='col-sm-10'>
              <%= f.text_field :name, class: "form-control", placeholder: "Name" %> 
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :email, nil, class: "col-sm-2 control-label" %> 
            <div class="col-sm-10">
              <%= f.text_field :email, class: "form-control", placeholder: "Email" %> 
            </div> 
          </div>
          <div class='form-group'>
            <%= f.label :password, nil, class: "col-sm-2 control-label" %> 
            <div class='col-sm-10'>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
          </div>
          <div class='col-md-offset-2'>
            <div class='form-group'>
              <div class='col-sm-offeset-2 col-sm-10'>
                <button type='submit' class='btn btn-primary'>Register</button>
              </div>
            </div>
          </div>
        <% end %> 
      </div>
    </div> <!-- row -->
  </div>  <!-- container -->
</div> <!-- main-content -->